language: node_js
node_js:
- 4.6.0
sudo: false
cache:
  directories:
  - node_modules
env:
  global:
  - APPLICATION_URI="http:\/\/example.com"
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
